# Generated by Django 4.1.8 on 2023-04-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Transgenders', 'Transgenders'), ('Male', 'Male')], max_length=25),
        ),
    ]
