# Generated by Django 4.1.8 on 2023-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_bio_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Transgenders', 'Transgenders'), ('Female', 'Female'), ('Male', 'Male')], max_length=25),
        ),
    ]
