# Generated by Django 4.1.8 on 2023-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_gender_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Transgenders', 'Transgenders'), ('Male', 'Male')], max_length=30),
        ),
    ]
