# Generated by Django 4.1.8 on 2023-04-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_gender_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgenders', 'Transgenders')], max_length=25),
        ),
    ]
