# Generated by Django 4.1.8 on 2023-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_followers_alter_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Transgenders', 'Transgenders'), ('Female', 'Female'), ('Male', 'Male')], max_length=25),
        ),
    ]
