# Generated by Django 4.1.8 on 2023-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Transgenders', 'Transgenders'), ('Male', 'Male'), ('Female', 'Female')], max_length=30),
        ),
    ]
