# Generated by Django 4.1.8 on 2023-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Transgenders', 'Transgenders'), ('Female', 'Female'), ('Male', 'Male')], max_length=30),
        ),
    ]
