# Generated by Django 4.1.8 on 2023-06-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Transgenders', 'Transgenders'), ('Male', 'Male')], max_length=30),
        ),
    ]
