# Generated by Django 4.1.8 on 2023-05-28 10:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
