# Generated by Django 4.1.8 on 2023-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.FileField(blank=True, null=True, upload_to='post/'),
        ),
    ]
