# Generated by Django 4.1.8 on 2023-06-15 14:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post/image'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='post/videos'),
        ),
    ]
