# Generated by Django 4.1.8 on 2023-05-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.FileField(blank=True, upload_to='post/'),
        ),
    ]
