# Generated by Django 4.1.8 on 2023-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_caption_alter_post_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.FileField(upload_to='post/'),
        ),
    ]
