# Generated by Django 4.1.8 on 2023-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=550, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=280, null=True)),
            ],
        ),
    ]
