version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/LinkUp
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=linkup"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=7156"

volumes:
  postgres_data:
