# # Use an official Python runtime as a parent image
# FROM python:3.9-buster

# # Set environment variables
# ENV PYTHONUNBUFFERED 1
# ENV PYTHONDONTWRITEBYTECODE 1

# # Set the working directory in the container
# WORKDIR /LinkUp

# # Copy the requirements file to the working directory
# COPY requirements.txt .

# # Install the required packages
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy the project files to the working directory
# COPY . .

# # Expose the port on which the Django development server will run (default: 8000)
# EXPOSE 8000

# # Run the Django development server
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
# # 